# Generated by Django 4.1 on 2022-10-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msbctracker', '0002_tracker_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='shipped',
        ),
    ]
