# Generated by Django 4.1 on 2022-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbctracker', '0003_remove_tracker_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='msbc_patch_api_call_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
