# Generated by Django 4.1 on 2022-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbctracker', '0005_tracker_numeric_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='numeric_status',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
